spring:
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
          #开启小写验证，默认根据服务名查找都是用的全大写
          lower-case-service-id: true
      routes: #配置路由路径
        - id: jkeeper-nacos
          uri: lb://jkeeper-nacos
          # 断言,路径相匹配的进行路由
          predicates:
            - Path=/jkeeper-nacos/**
          filters:
            - StripPrefix=1
        - id: jkeeper-auth
          uri: lb://jkeeper-auth
          predicates:
            - Path=/jkeeper-auth/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://192.168.1.1:8090/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: 192.168.1.103
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger-ui/**"
      - "/actuator/**"
      - "/jkeeper-auth/oauth/token"
logging:
  level:
    root: info
    com.kery.jkeeper: debug