spring:
  datasource:
    url: jdbc:mysql://192.168.1.106:3306/jkeeper?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
seata: # Seata配置
  enabled: true
  service:
    vgroupMapping:
      jkeeper_tx_group: default
  tx-service-group: jkeeper_tx_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.1.106:8848
      group: DEFAULT_GROUP
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
mybatis:
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    root: info
    com.kery.jkeeper: debug