user:
  name: Kery
  age: 18
#MInIO分布式对象存储
minio:
  endpoint: http://192.168.1.106:9000 #MinIO服务所在地址，注意:9000才能进行api的操作,9001是图形化管理界面
  bucketName: jkeeper #存储桶名称
  accessKey:  #访问的key
  secretKey:  #访问的秘钥
logging:
  level:
    root: info
  config: classpath:logback-spring.xml